routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListController;
use App\Http\Controllers\Auth\loginController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\layoutController;
use App\Http\Controllers\nameofController;
use App\Http\Middleware\CheckLogin;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/testuser',[loginController::Class,'testusers']);
Route::post('/testlogin',[loginController::Class,'testlogin'])->name('testlogin');
Route::post('/testauth',[loginController::Class,'testauthUser']);
Route::get('/logout',[loginController::Class,'testuserLogout']);
Route::get('/home',[loginController::Class,'home']);



Route::get('/login',[loginController::Class,'login'])->name('login');
Route::post('/auth',[loginController::Class,'authUser']);
Route::post('/signup',[loginController::Class,'userSignup']);
Route::get('/signupview',[loginController::Class,'signup']);



   Route::resource('/list',ListController::Class)->middleware('auth');
   Route::any('/deleteuser/{id}',[ListController::Class,'deleteUser'])->middleware('auth');
   Route::get('/logout',[loginController::Class,'userLogout'])->middleware('auth');


  // Route::get('/testdashboad',[loginController::Class,'authenticate']);
  
Route::get('/website',[loginController::Class,'website']);
Route::get('/website/Contect',[loginController::Class,'websiteContect']);
Route::get('/website/About',[loginController::Class,'websiteAbout']);
Route::get('/website/Portfolio',[loginController::Class,'websitePortfolio']);


Route::get('/layout',[layoutController::Class,'layout']);
Route::get('/layout/Feedback',[layoutController::Class,'layoutFeedback']);
Route::get('/layout/About',[layoutController::Class,'layoutAbout']);
// Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
// Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
Route::get('/layout/AddFeedback',[layoutController::Class,'layoutAddFeedback'])->middleware('auth','CheckLogin');
Route::get('/layout/accountpage',[layoutController::Class,'layoutAccountpage']);

Route::post('/layout/Signup',[layoutController::Class,'layoutSignup']);
Route::post('/layout/store',[layoutController::Class,'storedata']);
Route::post('/layout/Login',[layoutController::Class,'layoutLogin']);
Route::get('/layout/Logout',[layoutController::Class,'layoutLogout'])->middleware('auth');

Route::resource('/array',nameofController::Class);
Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);

// Route::group(["middleware" => ["apprestrict"]], function(){
//   Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
//   Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
  
// });

Route::resource('/employee',EmployeeController::Class);

Route::any('/deleteEmployee/{id}',[CuserContraller::Class,'deleteEmployee']);

app/Models/TodoList.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TodoList extends Model
{
    use HasFactory;
    protected $fillable=[
        'name',
        'content'
    ];
}

resources/views/TodoList/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>

    </style>
</head>
<body>
<form method="post" action="{{ route('list.store')}}">
@csrf

<div class="container m-5 p-2 rounded mx-auto bg-light shadow">
    <!-- App title section -->
    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                <i class="fa fa-check bg-primary text-white rounded p-2"></i>
                <u>My Todo-s</u>
            </div>
        </div>
    </div>
    <!-- Create todo section -->
    <div class="mb-3" >
  <label for="Title" class="form-label">User</label>
  <select name="user_id" id="" class="form-control">
      <option value="">--Select user--</option>
      @if($test)
      @foreach($test as $user)
      <option value="{{$user->id}}">{{$user->email}}</option>
      @endforeach
      @endif
  </select>
  @error('user_id')
    <div class="alert alert-danger">{{ $message }}</div>
  @enderror
 </div>
 <div class="mb-3" >
  <label for="Title" class="form-label">Title</label>
  <input type="text" class="form-control" value="{{old('name')}}" id="to" placeholder="add title" name="name">
  @error('name')
    <div class="alert alert-danger">{{ $message }}</div>
  @enderror
 </div>
 <div class="mb-3">
  <label for="Discription" class="form-label">Discription</label>
  <textarea class="form-control" id="do" rows="3" name="content" >{{old('content')}}</textarea>
  @error('content')
    <div class="alert alert-danger">{{ $message }}</div>
  @enderror
 </div>
 <br>
    <button type="submit" class="btn btn-primary">Add</button>
</div>
</form>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

resources/views/TodoList/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Edit List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>

    </style>
</head>
<body>
<form method="post" action="{{ route('list.update',[$tedit->id])}}">
@method('PATCH')
@csrf

<div class="container m-5 p-2 rounded mx-auto bg-light shadow">
    <!-- App title section -->
    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                <i class="fa fa-check bg-primary text-white rounded p-2"></i>
                <u>My Todo-s</u>
            </div>
        </div>
    </div>
    <!-- Create todo section -->

 <div class="mb-3">
  <label for="Title" class="form-label">Title</label>
  <input type="text" class="form-control" placeholder="add title" name="name" value = "{{$tedit->name}}">
  @error('name')
    <div class="alert alert-danger">{{ $message }}</div>
  @enderror
</div>
 <div class="mb-3">
  <label for="Discription" class="form-label">Discription</label>
  <textarea type="text"  class="form-control" rows="3" name="content" value ="">{{$tedit->content}}</textarea>
  @error('content')
    <div class="alert alert-danger">{{ $message }}</div>
  @enderror
</div>
 <br>
    <button type="submit" class="btn btn-primary">Save Change</button>
</div>
</form>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

resources/views/TodoList/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>List Data</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>List Data</h2>
             
  <table class="table">
    <thead>
      <tr>
        <th>S No.</th>
        <th>Title</th>
        <th colspan="2">content</th>
      </tr>
    </thead>
    <tbody>
    @foreach($data as $listdata)
      <tr>
      <th scope="row">{{ $loop->iteration}}</th>
        <td>{{$listdata->name}}</td>
        <td colspan="2">{{$listdata->content}}</td>
        <td>
        <a href="{{ route('list.edit',[$listdata->id])}}" class="btn btn-primary btn-sm">edit</a>
        <a href="{{ url('deleteuser/'.$listdata->id)}}" calss="btn btn-danger btn-sm"> Delete</a>
     
      </td>
      </tr>
      @endforeach
     
    </tbody>
  </table>
  <div>
     <a href="{{ route('list.create')}}" class="btn btn-primary btn-sm"> Add List </a>
     <a href="{{ url('/logout')}}" class="btn btn-primary btn-sm"> Logout </a>
    </div>


  @foreach($test as $user)
  @foreach($user->getTodoList as $todo)
  {{$todo->name}}
  @endforeach
  @endforeach
</div>

</body>
</html>