routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListController;
use App\Http\Controllers\Auth\loginController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\layoutController;
use App\Http\Controllers\nameofController;
use App\Http\Middleware\CheckLogin;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/testuser',[loginController::Class,'testusers']);
Route::post('/testlogin',[loginController::Class,'testlogin'])->name('testlogin');
Route::post('/testauth',[loginController::Class,'testauthUser']);
Route::get('/logout',[loginController::Class,'testuserLogout']);
Route::get('/home',[loginController::Class,'home']);



Route::get('/login',[loginController::Class,'login'])->name('login');
Route::post('/auth',[loginController::Class,'authUser']);
Route::post('/signup',[loginController::Class,'userSignup']);
Route::get('/signupview',[loginController::Class,'signup']);



   Route::resource('/list',ListController::Class)->middleware('auth');
   Route::any('/deleteuser/{id}',[ListController::Class,'deleteUser'])->middleware('auth');
   Route::get('/logout',[loginController::Class,'userLogout'])->middleware('auth');


  // Route::get('/testdashboad',[loginController::Class,'authenticate']);
  
Route::get('/website',[loginController::Class,'website']);
Route::get('/website/Contect',[loginController::Class,'websiteContect']);
Route::get('/website/About',[loginController::Class,'websiteAbout']);
Route::get('/website/Portfolio',[loginController::Class,'websitePortfolio']);


Route::get('/layout',[layoutController::Class,'layout']);
Route::get('/layout/Feedback',[layoutController::Class,'layoutFeedback']);
Route::get('/layout/About',[layoutController::Class,'layoutAbout']);
// Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
// Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
Route::get('/layout/AddFeedback',[layoutController::Class,'layoutAddFeedback'])->middleware('auth','CheckLogin');
Route::get('/layout/accountpage',[layoutController::Class,'layoutAccountpage']);

Route::post('/layout/Signup',[layoutController::Class,'layoutSignup']);
Route::post('/layout/store',[layoutController::Class,'storedata']);
Route::post('/layout/Login',[layoutController::Class,'layoutLogin']);
Route::get('/layout/Logout',[layoutController::Class,'layoutLogout'])->middleware('auth');

Route::resource('/array',nameofController::Class);
Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);

// Route::group(["middleware" => ["apprestrict"]], function(){
//   Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
//   Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
  
// });

Route::resource('/employee',EmployeeController::Class);

Route::any('/deleteEmployee/{id}',[CuserContraller::Class,'deleteEmployee']);

resources/views/empData/employee.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha256-aAr2Zpq8MZ+YA/D6JtRD3xtrwpEz2IqOS+pWD/7XKIw=" crossorigin="anonymous" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha256-OFRAJNoaD8L3Br5lglV7VyLRf0itmoBzWUoM+Sji4/8=" crossorigin="anonymous"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>




<style>
body {
  margin: 0;
  min-width: 250px;
  font-family: 'Sofia';font-size: 22px;
}

/* Include the padding and border in an element's total width and height */
* {
  box-sizing: border-box;
}

/* Style the close button */
.close {
  position: absolute;
  right: 0;
  top: 0;
  padding: 12px 16px 12px 16px;
}

.close:hover {
  background-color: #f44336;
  color: white;
}

/* Style the header */
.header {
  background-color: #f44336;
  padding: 30px 40px;
  color: white;
  text-align: center;
}

/* Clear floats after the header */
.header:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the input */
input ,select {
  margin: 5px;
  color:black;
  border: none;
  border-radius: 0;
  width: 30%;
  padding: 10px;
  float: left;
  font-family: 'Sofia';font-size: 22px;
  font-size: 18px;
}

/* Style the "Add" button */
.addBtn {
  padding: 10px;
  width: auto%;
  background: #d9d9d9;
  color: #555;
  float: right;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.addBtn:hover {
  background-color: #bbb;
}
.addSkills input{
  margin: 5px;
  color:black;
  border: none;
  border-radius: 0;
  width: auto;
  padding: 10px;
  float: left;
  font-family: 'Sofia';font-size: 22px;
  font-size: 16px;
}
.shosha{
  margin: 5px;
  color:white;
  border: none;
  border-radius: 0;
  width: auto;
  padding: 10px;
  float: left;
  font-size: 16px;
}
.backBtn{
  padding: 10px;
  width: auto%;
  background: #d9d9d9;
  color: #555;
  float: left;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}
/* 
.custom-select {
  position: relative;
  font-family: Arial;
}

.custom-select select {
  display: none;
}

.select-selected {
  background-color: DodgerBlue;
}


.select-selected:after {
  position: absolute;
  content: "";
  top: 14px;
  right: 10px;
  width: 0;
  height: 0;
  border: 6px solid transparent;
  border-color: #fff transparent transparent transparent;
}


.select-selected.select-arrow-active:after {
  border-color: transparent transparent #fff transparent;
  top: 7px;
}


.select-items div,.select-selected {
  color: #ffffff;
  padding: 8px 16px;
  border: 1px solid transparent;
  border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
  cursor: pointer;
  user-select: none;
}


.select-items {
  position: absolute;
  background-color: DodgerBlue;
  top: 100%;
  left: 0;
  right: 0;
  z-index: 99;
}


.select-hide {
  display: none;
}

.select-items div:hover, .same-as-selected {
  background-color: rgba(0, 0, 0, 0.1);
} */
</style>
</head>
<script>

// // Get the modal
// var modal = document.getElementById('id02');

// // When the user clicks anywhere outside of the modal, close it
// window.onclick = function(event) {
//     if (event.target == modal) {
//         modal.style.display = "none";
//     }
//   }

$(document).ready(function(){
$(".add_exp1").click(function(){
 
  var html =     '<div onclick="deleterow(this)" class="Input_Skill">'+
                 '<input type="text" id="skill_name" placeholder="Enter skill" name="skill_name[]" required>'+
                 '<select input type="text" id="status" placeholder="Enter status" name="status[]" required><option value="Beginner">Beginner</option><option value="Intermediate">Intermediate</option><option value="Expert">Expert</option></select>'+
                 '<select input type="text" name="experience[]" class ="m-write js-example-basic-multiple" placeholder="experience" multiple required>'+
                 '@foreach($exper as $experience)'+
                 '<option value="{{$experience->experience}}">{{$experience->experience}}</option>'+
                 '@endforeach <select>'+
                 '<i class="fa fa-close shosha btn_remove" name="remove" style="font-size:36px"></i>'+
                 '</div>';


  $("#admi").append(html);
}); 
$(document).on('click', '.btn_remove', function(){  
         //  var button_id = $(this).attr("id");   
           //$('#row'+button_id+'').remove();  
           function deleterow(e){
        $(e).parent().parent().parent().remove();
    }

      }); 
}); 



</script>
<body>

<div id="myDIV" class="header">
<span onclick="newElement()" class="add_exp1 btn addBtn">Add Skills</span>
<a href="{{ route('employee.index')}}" class="backBtn">back</a>
  <h2 style="margin:5px">Add Employee</h2>
  <form class="form-horizontal"  action="{{route('employee.store')}}" method="post">
  @csrf
  <input type="text" placeholder="Employee Name" name="name">
  @error('name')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <input type="text" placeholder="Mobile No." name="mobile">
  @error('mobile')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <input type="text" placeholder="designation" name="designation">
  @error('designation')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror

  
<div id="admi">    
 <br>
</div>
<br><br>
<button type="submit" class="btn addBtn">Submit</button>

</form>
</div>

<script type="text/javascript">

$(document).ready(function() {

    $('.category').select2();

});

</script>


</body>
</html>

resources/views/empData/index.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<style>
body {
  margin: 0;
  min-width: 250px;
  font-family: 'Sofia';font-size: 22px;
}

table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}

/* Include the padding and border in an element's total width and height */
* {
  box-sizing: border-box;
}
  



/* Style the close button */
.close {
  position: absolute;
  right: 0;
  top: 0;
  padding: 12px 16px 12px 16px;
}

.close:hover {
  background-color: #f44336;
  color: white;
}

/* Style the header */
.header {
  background-color: #f44336;
  padding: 30px 40px;
  color: white;
  text-align: center;
}
a{
  text-decoration: none;
  color:white;
  font-family: 'Sofia';font-size: 22px;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 10px 18px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: auto;
  font-family: 'Sofia';font-size: 22px;
}

a:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}
.viewbtn {

  width: auto;
  padding: 10px 18px;
  background-color: #e7e7e7;
   color: black;
}
.addbtn {

width: auto;
padding: 10px 10px;
background-color: #e7e7e7;

 color: black;
}


.addBtn {
  padding: 10px;
  width: auto;
  background: #d9d9d9;
  color: #555;
  float: left;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.addBtn:hover {
  background-color: #bbb;
}
.alert-success{
  padding: 10px;
  width: auto;
  background: #d9d9d9;
  color: green;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.alert-error{
  padding: 10px;
  width: auto;
  background: #d9d9d9;
  color: pink;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}
</style>

</head>
<body>

<div id="myDIV" class="header">
<a href="{{ route('employee.create')}}" class="addBtn">Add</a>
  <h2 style="margin:5px">Employee List</h2>
</div>
@if (Session::has('success'))
            <div class="alert alert-success text-center">
                <p1>{{ Session::get('success') }}</p1>
            </div>
            @endif 
            @if (Session::has('error'))
            <div class="alert alert-error">
              <p>{{session::get('error')}}</p>
            </div>
            @endif
<table>
    <th>Employee name </th>
    <th>Designation</th>
    <th>Mobile No.</th>
    <th></th>
    <th></th>
  </tr>

  @foreach($data as $user)
  <tr>
    <td>{{ $user->name}}</td>
    <td>{{ $user->designation}}</td>
    <td>{{ $user->mobile}}</td>
    <td><a href="{{route('employee.show',[$user->id])}}" class="viewbtn">view</td>
    <td>
      <form action="{{ route('employee.destroy',$user->id) }}" method="Post">
      <button class="btn btn-primary"><a href="{{ route('employee.edit',$user->id) }}">Edit</a></button>
@csrf
@method('DELETE')
<button type="submit" class=" cancelbtn">Delete</button>
</form>


    </td>
  </tr>
  @endforeach
</table>


</script>

</body>
</html>

resources/views/empData/update.blade.php
<!DOCTYPE html>
<html>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha256-aAr2Zpq8MZ+YA/D6JtRD3xtrwpEz2IqOS+pWD/7XKIw=" crossorigin="anonymous" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha256-OFRAJNoaD8L3Br5lglV7VyLRf0itmoBzWUoM+Sji4/8=" crossorigin="anonymous"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>


<style>


body {
  margin: 0;
  min-width: 250px;
  font-family: 'Sofia';font-size: 22px;
}

/* Include the padding and border in an element's total width and height */
* {
  box-sizing: border-box;
}

/* Style the close button */
.close {
  position: absolute;
  right: 0;
  top: 0;
  padding: 12px 16px 12px 16px;
}

.close:hover {
  background-color: #f44336;
  color: white;
}

/* Style the header */
.header {
  background-color: #f44336;
  padding: 30px 40px;
  color: white;
  text-align: center;
}

/* Clear floats after the header */
.header:after {
  content: "";
  display: table;
  clear: both;
}

.backBtn{
  padding: 10px;
  width: auto%;
  background: #d9d9d9;
  color: #555;
  float: left;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}



/* Style the input */
input ,select {
  margin: 5px;
  color:black;
  border: none;
  border-radius: 0;
  width: 30%;
  padding: 10px;
  float: left;
  font-family: 'Sofia';font-size: 22px;
  font-size: 18px;
}

/* Style the "Add" button */
.addBtn {
  padding: 10px;
  width: auto%;
  background: #d9d9d9;
  color: #555;
  float: right;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.addBtn:hover {
  background-color: #bbb;
}
.addSkills input{
  margin: 5px;
  color:black;
  border: none;
  border-radius: 0;
  width: auto;
  padding: 10px;
  float: left;
  font-family: 'Sofia';font-size: 22px;
  font-size: 16px;
}
.shosha{
  margin: 5px;
  color:white;
  border: none;
  border-radius: 0;
  width: auto;
  padding: 10px;
  float: left;
  font-size: 16px;
}
select input{
  margin: 5px;
  color:black;
  border: none; 
  border-radius: 0;
  width: 12%;
  padding: 1px;
  float: left;
  font-size: 16px;

}
.m-write{
   margin: 5px;
  color:black;
  border: none; 
  border-radius: 0;
  width: 12%;
  padding: 1px;
  float: left;
  font-size: 16px;

}
</style>
</head>
<script>
$(document).ready(function(){
$(".add_exp1").click(function(){
 
  var html =     '<div class="Input_Skill">'+
                 '<input type="text" id="skill_name" placeholder="Enter skill" name="skill_name[]" required>'+
                 '<select input type="text" id="status" class ="js-example-basic-multiple"  multiple="multiple" placeholder="Enter status" name="status[]" required><option value="Beginner">Beginner</option><option value="Intermediate">Intermediate</option><option value="Expert">Expert</option></select>'+
                 '<select input type="text" name="experience[]" class ="js-example-basic-multiple"  multiple="multiple" placeholder="experience" required>'+
                 '@foreach($exper as $experience)'+
                 '<option value="{{$experience->experience}}">{{$experience->experience}}</option>'+
                 '@endforeach <select>'+
                 '<i class="fa fa-close shosha btn_remove" name="remove" style="font-size:36px"></i>'+
                 '</div>';


  $("#admi").append(html);
}); 
$(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      }); 
}); 

</script>
<body>

<div id="myDIV" class="header">
<a href="{{ route('employee.index')}}" class="backBtn">back</a>
<span onclick="newElement()" class="add_exp1 btn addBtn">Add Skills</span>
  <h2 style="margin:5px">Update Employee</h2>
  <form class="form-horizontal" action="{{route('employee.update',[$user->id])}}" method="post">
  @method('PATCH')
  @csrf
  <input type="text" placeholder="Employee Name" name="name" value="{{ $user->name}}">
  @error('name')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <input type="text" placeholder="Mobile No." name="mobile" value="{{ $user->mobile}}">
  @error('mobile')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror
  <input type="text" placeholder="designation" name="designation" value="{{ $user->designation}}">
  @error('designation')
  <div class="alert alert-danger">{{ $message }}</div>
  @enderror
 
  @foreach($skill as $key =>  $user2)   
  <div class="Input_Skill">
                 <input type="text" id="skill_name" placeholder="Enter skill" name="skill_name[]" value="{{ $user2->skill_name}}" required>
                 <select input type="text" id="status" class ="m-write js-example-basic-multiple "  multiple="multiple" placeholder="Enter status" name="status[]" value="" required >
                 <option value="">Select status </option>
                 <option value="Beginner" {{ ($user2->status) == 'Beginner' ? 'selected' : ''}}>Beginner</option>
                 <option value="Intermediate" {{ ($user2->status) == 'Intermediate' ? 'selected' : ''}}>Intermediate</option>
                 <option value="Expert" {{ ($user2->status) == 'Expert' ? 'selected' : ''}}>Expert</option></select>
                 <select input type="text" name="experience[]"  multiple="multiple" class ="m-write js-example-basic-multiple" placeholder="experience" value="{{ $user2->experience}}" required>
                   @foreach($exper as $experience)
                 <option value="{{$experience->experience}}" @if($experience->experience == $user2->experience) selected @endif>{{$experience->experience}}</option>
                 @endforeach
                </select>
                 <!-- <i class="fa fa-close shosha btn_remove" name="remove" style="font-size:36px"></i> -->
                 </div> @endforeach
  

<script>$(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});</script>
            
<div id="admi">   

 <br>
</div>
<br><br>
<button type="submit" class="btn addBtn">Submit</button>

</form>
</div>



</body>
</html>

resources/views/empData/viewdata.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<style>
body {
  margin: 0;
  min-width: 250px;
  font-family: 'Sofia';font-size: 22px;
}

table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}

/* Include the padding and border in an element's total width and height */
* {
  box-sizing: border-box;
}
  



/* Style the close button */
.close {
  position: absolute;
  right: 0;
  top: 0;
  padding: 12px 16px 12px 16px;
}

.close:hover {
  background-color: #f44336;
  color: white;
}

/* Style the header */
.header {
  background-color: #f44336;
  padding: 30px 40px;
  color: white;
  text-align: center;
}

a {
  background-color: #04AA6D;
  color: white;
  padding: 10px 18px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: auto;
}

a:hover {
  opacity: 0.8;
}

.showdata {

width: auto;
padding: 10px 10px;
float: right;
 color: black;
}


.addBtn {
  padding: 10px;
  width: auto;
  background: #d9d9d9;
  color: #555;
  float: left;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  transition: 0.3s;
  border-radius: 0;
}

.addBtn:hover {
  background-color: #bbb;
}
</style>

</head>
<body>

<div id="myDIV" class="header">
<a href="{{ route('employee.index')}}" class="addBtn">back</a>
  <h2 style="margin:5px">{{ $employee->name}} Details</h2>
  <h3 class="showdata">Contact NO. {{ $employee->mobile}}</h3>
</div>

<table>
  <tr>
    <th>Skill Name </th>
    <th>Status</th>
    <th>experience</th>
    <th></th>
  </tr>
  @foreach($skill as $user)
  <tr>
    <td>{{ $user->skill_name}}</td>
    <td>{{ $user->status}}</td>
    <td>{{ $user->experience}}</td>
  </tr>
  @endforeach

</table>

</body>
</html>