routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListController;
use App\Http\Controllers\Auth\loginController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\layoutController;
use App\Http\Controllers\nameofController;
use App\Http\Middleware\CheckLogin;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/testuser',[loginController::Class,'testusers']);
Route::post('/testlogin',[loginController::Class,'testlogin'])->name('testlogin');
Route::post('/testauth',[loginController::Class,'testauthUser']);
Route::get('/logout',[loginController::Class,'testuserLogout']);
Route::get('/home',[loginController::Class,'home']);



Route::get('/login',[loginController::Class,'login'])->name('login');
Route::post('/auth',[loginController::Class,'authUser']);
Route::post('/signup',[loginController::Class,'userSignup']);
Route::get('/signupview',[loginController::Class,'signup']);



   Route::resource('/list',ListController::Class)->middleware('auth');
   Route::any('/deleteuser/{id}',[ListController::Class,'deleteUser'])->middleware('auth');
   Route::get('/logout',[loginController::Class,'userLogout'])->middleware('auth');


  // Route::get('/testdashboad',[loginController::Class,'authenticate']);
  
Route::get('/website',[loginController::Class,'website']);
Route::get('/website/Contect',[loginController::Class,'websiteContect']);
Route::get('/website/About',[loginController::Class,'websiteAbout']);
Route::get('/website/Portfolio',[loginController::Class,'websitePortfolio']);


Route::get('/layout',[layoutController::Class,'layout']);
Route::get('/layout/Feedback',[layoutController::Class,'layoutFeedback']);
Route::get('/layout/About',[layoutController::Class,'layoutAbout']);
// Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
// Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
Route::get('/layout/AddFeedback',[layoutController::Class,'layoutAddFeedback'])->middleware('auth','CheckLogin');
Route::get('/layout/accountpage',[layoutController::Class,'layoutAccountpage']);

Route::post('/layout/Signup',[layoutController::Class,'layoutSignup']);
Route::post('/layout/store',[layoutController::Class,'storedata']);
Route::post('/layout/Login',[layoutController::Class,'layoutLogin']);
Route::get('/layout/Logout',[layoutController::Class,'layoutLogout'])->middleware('auth');

Route::resource('/array',nameofController::Class);
Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);

// Route::group(["middleware" => ["apprestrict"]], function(){
//   Route::get('/layout/Project',[layoutController::Class,'layoutProject']);
//   Route::get('/layout/Contact',[layoutController::Class,'layoutContact']);
  
// });

Route::resource('/employee',EmployeeController::Class);

Route::any('/deleteEmployee/{id}',[CuserContraller::Class,'deleteEmployee']);

resources/views/array/data.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>



  <script>
// $(document).ready(function(){
// $(".add_exp1").click(function(){
//   //alert("hello");
//   var html = "";
//                 html += '<label class="control-label col-sm-2" for="id">Admission Id:</label>';
//                 html += '<div class="col-sm-2">';
//                 html += '<input type="number" class="form-control" id="id" placeholder="Enter id" name="admission_id[]">';
//                 html += '<div class="col-sm-2">';
//                 html += '<label class="control-label col-sm-2" for="pwd">Student Name:</label>';
//                 html += '<input type="text" class="form-control" id="name" placeholder="Enter name" name="name[]">';
//                 html += '</div>';
// 				});      
// $('#admi').append(html);
// });









$(document).ready(function(){
$(".add_exp1").click(function(){
 
  var html =     
                 '<label class="control-label col-sm-2" for="id">Admission Id:</label>'+
                 '<div class="col-sm-4">'+
                 '<input type="number" class="form-control" id="id" placeholder="Enter id" name="admission_id[]">'+
                 '</div>'+
                 '<label class="control-label col-sm-2" for="Name">Student Name:</label>'+
                 '<div class="col-sm-4">'+
                 '<input type="text" class="form-control" id="name" placeholder="Enter name" name="name[]"><br>'+
                 '</div>';



  $("#admi").append(html);
});   
});

</script>
</head>
<body>

<div class="container">
  <h2>Horizontal form</h2>

  <div><button  class="add_exp1 btn btn-default">+</button></div>
  <form class="form-horizontal"  action="{{route('array.store')}}" method="post">
  @csrf

    <div class="form-group">

      <label class="control-label col-sm-2" for="admission_id">Admission Id:</label>
      <div class="col-sm-4">
        <input type="number" class="form-control" id="admission_id" placeholder="Enter id" name="admission_id[]">
      </div>
    
      <label class="control-label col-sm-2" for="name">Student Name:</label>
      <div class="col-sm-4">          
        <input type="text" class="form-control" id="name" placeholder="Enter name" name="name[]">
        <br>
      </div>
      

      <div id="admi">
      
      </div>
      
      <br>
      <br>
      <div class="col-sm-offset-2 col-sm-2">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
</div>

</body>
</html>